# Write your MySQL query statement below
WITH STD_SUB AS(
    SELECT STUDENTS.STUDENT_ID AS STUDENT_ID
            , STUDENTS.STUDENT_NAME AS STUDENT_NAME
            , SUBJECTS.SUBJECT_NAME AS SUBJECT_NAME
    FROM STUDENTS, SUBJECTS
    ORDER BY STUDENTS.STUDENT_ID, SUBJECTS.SUBJECT_NAME
)

SELECT STD_SUB.STUDENT_ID, STD_SUB.STUDENT_NAME, STD_SUB.SUBJECT_NAME
,COALESCE(COUNT(EXAMINATIONS.STUDENT_ID),0) AS attended_exams
FROM STD_SUB
LEFT JOIN EXAMINATIONS
ON STD_SUB.STUDENT_ID = EXAMINATIONS.STUDENT_ID
AND STD_SUB.SUBJECT_NAME = EXAMINATIONS.SUBJECT_NAME
GROUP BY 1,2,3
ORDER BY 1,3
